### ISSUE TITLE
Directly use this feature without manually install npm breaks the installation procedure

### ISSUE THREAD

**Issue by yf-yang** [NicoVIII/devcontainer-features#2]
In common devcontainer/devcontainer-contrib features, e.g. [jest](https://github.com/devcontainers-contrib/features/blob/006e18efa8d69a0e0097ada514e11449bfcd0ce6/src/jest/install.sh#L33), they check whether npm is installed and install one if needed (those codes are based on [feature template](https://github.com/devcontainers-contrib/features/blob/main/pkgs/feature-template/%7B%7Bcookiecutter.base_dir%7D%7D/src/%7B%7Bcookiecutter.feature_id%7D%7D/install.sh)).

Now unfortunately, when using a .devcontainer.json with only `image` and `features` specified, unfortunately (I don't know why) this feature is executed first, so no npm is installed and the whole procedure breaks.

I can also provide a PR.

**Comment by NicoVIII** [comment]
That sounds like a very good idea!
Feel free to create a PR, I will look into it :)
