### ISSUE TITLE
$VERSION is used by both node and pnpm

### ISSUE THREAD

**Issue by EliiseS** [NicoVIII/devcontainer-features#6]
## Description

The `$VERSION` in [`install.sh`](https://github.com/NicoVIII/devcontainer-features/blob/main/src/pnpm/install.sh) is used in both the pnpm installation and by the node installation

```sh
# install.sh
PNPM=${VERSION:-"latest"}
```

## Reproduction

You can repro this by setting the version to anything that doesn't exist on node:

```sh
"features": {
    "ghcr.io/NicoVIII/devcontainer-features/pnpm:2": {
          "version": "0.27.1"
    }
}
```
Which will then result in an error like this

```sh
#0 7.863 => Append the following lines to the correct file yourself:
#0 7.863 
#0 7.863 export NVM_DIR="/usr/local/share/nvm"
#0 7.863 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#0 7.863 
#0 7.884 => Installing Node.js version 0.27.1
#0 8.457 Version '0.27.1' not found - try `nvm ls-remote` to browse available versions.
#0 8.504 Failed to install Node.js 0.27.1
#0 8.504 => Close and reopen your terminal to start using nvm or run the following to use it now:
#0 8.504 
#0 8.504 export NVM_DIR="/usr/local/share/nvm"
#0 8.504 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#0 8.567 ! WARNING: Version '0.27.1' does not exist.
#0 8.576 default -> 0.27.1 (-> N/A)
#0 8.578 Updating /etc/bash.bashrc and /etc/zsh/zshrc...
```

## Solution

You can unset the `VERSION` or set it to be 'latest' before running line `curl -fsSL https://raw.githubusercontent.com/devcontainers/features/main/src/node/install.sh | $SHELL`

## Notes

I saw you want to move over to the other repo and they have a different system for this implementation now, so this may be a non issue for you :)

**Comment by NicoVIII** [comment]
Thanks for bringing this up!
I will look into this and either fix this here or move to the other repo first, whatever is easier :smile:

**Comment by NicoVIII** [comment]
I chose to simply add a test for this issue and add a simple unset. This worked 👍 
I will release shortly as v2.0.1.
