### ISSUE TITLE
Provide options in devcontainer.json for store-dir and virtual-store-dir

### ISSUE THREAD

**Issue by Supportic** [NicoVIII/devcontainer-features#7]
PNPM benefits come from symlinking existing packages into your curent project.
Working with docker, creates the necessity to store your global pnpm store in a volume in order to reuse them.

Usually one would create an .npmrc file to store these variables so that pnpm knows where to look at.
(This is also done when executing `pnpm config set store-dir <PATH>` and `pnpm config set virtual-store-dir <PATH>`. The file will be created in the current PWD)
PNPM looks at different places for that file. If there is nothing in your project directory, it will look in $HOME which depends on the current user. Currently before I can reuse my packages I always have to execute these lines when building the container:

```Dockerfile
ARG PROJECT_NAME=demo

# set pnpm store locations
# store-dir = global store
RUN cd ~ \
  && mkdir .pnpm \
  && pnpm config set store-dir ~/.pnpm/${PROJECT_NAME}/store \
  && pnpm config set virtual-store-dir ~/.pnpm/${PROJECT_NAME}/node_modules/.pnpm
```

Setting the global store as part of the config, would eliminate this step and ~/.pnpm/store would be read from the volume.

ref:
- https://pnpm.io/configuring
- https://pnpm.io/npmrc#node-modules-settings

**Comment by NicoVIII** [comment]
Thank you for the suggestion!

If #4 takes too long or is rejected, I will look into this :)

**Comment by NicoVIII** [comment]
This feature was moved into devcontainers-contrib:
https://github.com/devcontainers-contrib/features/issues/265

Therefore the version in this repo is deprecated.
I suggest that you repeat your feature request over there, maybe the new maintainer will add it. :)
